### ISSUE TITLE
Which is the folder?

### ISSUE THREAD

**Issue by Z-fly** [FZFalzar/NikkeTools#1]
![image](https://user-images.githubusercontent.com/10470892/201840169-15dfe21a-ec78-4a0e-b86e-f08ff8b9ec22.png)
![image](https://user-images.githubusercontent.com/10470892/201839378-883dc043-830f-4904-9cdc-4f8c96a0710a.png)

For example, I want to revert this file.
![image](https://user-images.githubusercontent.com/10470892/201840068-ef3b4608-31cf-4350-af48-e0ef70388219.png)
What should I do?

**Comment by FZFalzar** [comment]
The tool is only for files within the /eb folder. It will not work with files in any other folder, unless they are also NKAB.

If by revert you mean you want to use the original from the game with no mods, then just delete the file and let it re-download again

**Comment by Z-fly** [comment]
I mean
this ![image](https://user-images.githubusercontent.com/10470892/201881161-d024be15-77b9-4009-9ed8-896aa5523a2c.png)
revert to
![image](https://user-images.githubusercontent.com/10470892/201881269-9cfb536c-dd36-415c-83f6-e5254d28d054.png)

**Comment by FZFalzar** [comment]
This place is for raising questions about the tool, not how to do the actual modding. Besides:

1) The bones could be different from what is used in NIKKE.  
2) Copyright Issues, especially since you're trying to take a GFL skeleton 

Good luck if you manage to get it to work, but I sure hope you don't release it and get yourself into trouble with MICA

**Comment by FZFalzar** [comment]
Also I might have misread, use a Spine viewer to load the atlas/skel and view it.

**Comment by Z-fly** [comment]
https://nikke-db.github.io/v
This?
