### ISSUE TITLE
Can't open .exe

### ISSUE THREAD

**Issue by Chambalam** [FZFalzar/NikkeTools#8]
Hi. I checked the resolved issues before posting but none seem to fit what's happening with me.

Downloaded the exe, made sure to check the requirements. Downloaded and installed the .net core 7.0, restarted computer to make sure. Followed instructions to drag the /eb folder onto the exe, nothing happened. Attempted to open the .exe, a quick flash of a black box would appear, then disappear just as quickly. Tried deleting and re downloading, still the same issue however

**Comment by FZFalzar** [comment]
Please check the /eb folder for the decrypted files, if any. They should have the "_dec.bundle" added to the back of the name if the operation succeeded. The program is not meant to be executed directly since there is no GUI. If you wish to examine any messages it outputs, run it in a command prompt

**Comment by Chambalam** [comment]
> Please check the /eb folder for the decrypted files, if any. They should have the "_dec.bundle" added to the back of the name if the operation succeeded. The program is not meant to be executed directly since there is no GUI. If you wish to examine any messages it outputs, run it in a command prompt

all sorted thanks. Turns out in my case the SDk 3.1 or later wasn't quite accurate, it had to be exactly 3.1 and none other lmao
